Exact solutions for both MDPs and DTMCs using linear programming.
External GLPK library added for solving lp problems. The library GMP is used for providing arbitrary precision arithmetic.

diff --git a/prism/Makefile b/prism/Makefile
--- a/prism/Makefile
+++ b/prism/Makefile
@@ -298,11 +298,46 @@ MAKE_DIRS = dd jdd odd dv prism mtbdd sparse hybrid parser settings userinterfac
 
 EXT_PACKAGES = lpsolve55 lp_solve_5.5_java
 
+EXACT_LP_PACKAGES = glpk glpk_java
+
+EXACT_LP_REQUIREMENTS_INSTALLED = 1
+
+# Find glpk_java requirements
+DETECT_SWIG = $(shell which swig 2> /dev/null)
+DETECT_MVN = $(shell which mvn 2> /dev/null)
+DETECT_LIBTOOL = $(shell which libtool 2> /dev/null)
+DETECT_ACLOCAL = $(shell which aclocal 2> /dev/null)
+
+ifeq ($(DETECT_SWIG),)
+	EXACT_LP_REQUIREMENTS_INSTALLED = 0
+endif
+ifeq ($(DETECT_MVN),)
+	EXACT_LP_REQUIREMENTS_INSTALLED = 0
+endif
+ifeq ($(DETECT_LIBTOOL),)
+	EXACT_LP_REQUIREMENTS_INSTALLED = 0
+endif
+ifeq ($(DETECT_ACLOCAL),)
+	EXACT_LP_REQUIREMENTS_INSTALLED = 0
+endif
+
 .PHONY: clean javadoc tests
 
 default: all
 
-all: cuddpackage extpackages prism
+all: cuddpackage extpackages exact_lp_requirements exact_lp prism
+
+exact_lp_requirements: checks
+	cp ext/glpk_java/jar/glpk-java.jar lib
+	@if [ "$(DETECT_SWIG)" != "" ]; then echo "Found SWIG in $(DETECT_SWIG)"; \
+	else echo "Warning: SWIG not found. Required for GLPK java bindings."; fi
+	@if [ "$(DETECT_MVN)" != "" ]; then echo "Found MAVEN in $(DETECT_MVN)"; \
+	else echo "Warning: MAVEN not found. Required for GLPK java bindings."; fi
+	@if [ "$(DETECT_LIBTOOL)" != "" ]; then echo "Found LIBTOOL in $(DETECT_LIBTOOL)"; \
+	else echo "Warning: LIBTOOL not found. Required for GLPK java bindings."; fi
+	@if [ "$(DETECT_ACLOCAL)" != "" ]; then echo "Found ACLOCAL in $(DETECT_ACLOCAL)"; \
+	else echo "Warning: ACLOCAL not found. Required for both GLPK and GLPK java bindings."; fi
+	@sed -i '/EXACT_LP_REQUIREMENTS_INSTALLED/c\	public final int EXACT_LP_REQUIREMENTS_INSTALLED = $(EXACT_LP_REQUIREMENTS_INSTALLED);' src/prism/PrismSettings.java;
 
 cuddpackage: checks
 	@if [ "$(CUDD_DIR)" = "" ]; then echo "Error: Cannot find CUDD"; exit 1; fi
@@ -359,6 +394,25 @@ extpackages: checks
 	  JAVA_JNI_MD_H_DIR="$(JAVA_JNI_MD_H_DIR)" \
 	  ) || exit 1; \
 	done
+
+exact_lp: checks
+	@(if [ "$(EXACT_LP_REQUIREMENTS_INSTALLED)" = 1 ]; then \
+	  for ext in $(EXACT_LP_PACKAGES); do \
+           echo Making $$ext; \
+           (cd ext/$$ext && \
+           $(MAKE) \
+           OSTYPE="$(OSTYPE)" \
+           ARCH="$(ARCH)" \
+           LIBPREFIX="$(LIBPREFIX)" \
+           LIBSUFFIX="$(LIBSUFFIX)" \
+           LIBMATH="$(LIBMATH)" \
+           BINDISTSUFFIX="$(BINDISTSUFFIX)" \
+           JAVA_DIR="$(JAVA_DIR)" \
+           JAVA_JNI_H_DIR="$(JAVA_JNI_H_DIR)" \
+           JAVA_JNI_MD_H_DIR="$(JAVA_JNI_MD_H_DIR)" \
+           ) || exit 1; \
+	  done \
+	fi)
 
 prism: checks make_dirs bin_scripts
 
@@ -543,7 +597,7 @@ clean_cudd:
 	@(cd $(CUDD_DIR) && $(MAKE) distclean)
 
 clean_ext:
-	@(for ext in $(EXT_PACKAGES); do \
+	@(for ext in $(EXT_PACKAGES) $(EXACT_LP_PACKAGES); do \
 	  echo Cleaning $$ext ...; \
 	  (cd ext/$$ext && \
 	  $(MAKE) -s LIBPREFIX="$(LIBPREFIX)" LIBSUFFIX="$(LIBSUFFIX)" clean) \
